POST  http://localhost:5000/users/users/add/ HTTP/1.1
Content-Type: application/json

{
        "name": "Admin Adminoija",
        "email": "admin@sysadmin.fi",
        "password": "admin",
        "role": "admin"
}