POST  http://localhost:5000/book/ HTTP/1.1
Content-Type: application/json

{
        "isbn": "0679722769",
        "title": "Ulysses",
        "author": "James Joyce",
        "published": "1922-02-02T00:00:00.000Z",
        "pages": 730,
        "description": "Ulysses is a modernist novel by Irish writer James Joyce. It was first serialised in parts in the American journal The Little Review from March 1918 to December 1920 and then published in its entirety in Paris by Sylvia Beach on 2 February 1922, Joyce's 40th birthday.",
        "copies": [
            {
                "id": "1",
                "status": "in_library",
                "reserveList": []
            },
            {
                "id": "2",
                "status": "in_library",
                "reserveList": []
            },
            {
                "id":"3",
                "status": "in_library",
                "reserveList": []
            }
        ]
}
