POST  http://localhost:5000/book/ HTTP/1.1
Content-Type: application/json

{
    "isbn": "1498599656",
    "title": "Plato's Socrates on Socrates",
    "author": "Anne Marie Schultz",
    "published": "2020-03-18T22:00:00.000Z",
    "pages": 152,
    "description": "In Plato's Socrates on Socrates: Socratic Self-Disclosure and the Public Practice of Philosophy, Anne-Marie Schultz analyzes the philosophical and political implications of Plato’s presentation of Socrates’ self-disclosive speech in four dialogues: Theaetetus, Symposium, Apology, and Phaedo. Schultz argues that these moments of Socratic self-disclosure show that Plato’s presentation of “Socrates the narrator” is much more pervasive than the secondary literature typically acknowledges.",
    "copies": [
        {
            "status": "in_library",
            "reserveList": []
        },
        {
            "status": "in_library",
            "reserveList": []
        }
    ]
}
